title: Rust & Solana Blockchain Insights
description: Learn Rust and Solana blockchain development through tutorials and tips. Enroll in my Udemy course for expert guidance.
url: "https://junlian.github.io"
permalink: /:title/
paginate: 5

# Analytics Configuration
# Google Analytics 4 Measurement ID for visitor tracking
google_analytics: G-QQ6X3F3TWM

# Alternative Analytics (optional)
# plausible_domain: junlian.github.io

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
remote_theme: pages-themes/minimal
