title: Rust & Solana Blockchain Insights
description: Learn Rust and Solana blockchain development through tutorials and tips. Enroll in my Udemy course for expert guidance.
url: "https://junlian.github.io"
permalink: /:title/
paginate: 5
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
remote_theme: pages-themes/minimal
