title: Rust & Solana Blockchain Insights
description: Learn Rust and Solana blockchain development through tutorials and tips. Enroll in my Udemy course for expert guidance.
url: "https://junlian.github.io"
permalink: /:title/
paginate: 5

# Analytics Configuration
# Replace 'G-XXXXXXXXXX' with your actual Google Analytics 4 Measurement ID
# To get your GA4 ID: https://analytics.google.com -> Admin -> Data Streams -> Web -> Measurement ID
google_analytics: G-XXXXXXXXXX

# Alternative Analytics (optional)
# plausible_domain: junlian.github.io

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
remote_theme: pages-themes/minimal
